#!/bin/bash
set -e

export SELF=$1; shift
confd -onetime -backend env

if [ "$POSTGRES_UNIX_SOCKET" != "" ]; then
    while ! psql -h $POSTGRES_UNIX_SOCKET -U $POSTGRES_USERNAME -c 'select 1' > /dev/null 2>&1; do
        echo "Waiting for postgres to be available..."
        sleep 1
    done
fi

while [[ -n "$1" ]]; do
    CMD=$1; shift

    case "$CMD" in
    initdb)
        echo "initialize storage (postgres) -h $POSTGRES_UNIX_SOCKET -U $POSTGRES_USERNAME -d $POSTGRES_DBNAME"
        if createdb -h $POSTGRES_UNIX_SOCKET -U $POSTGRES_USERNAME $POSTGRES_DBNAME; then
            stellar-core --newdb
        fi
        ;;
    printcfg)
        # for test
        cat /opt/stellar-core/stellar-core.cfg
        ;;
    genseed)
        stellar-core --genseed
        ;;
    forcescp)
        stellar-core --forcescp
        ;;
    newhist)
        stellar-core --newhist $SELF || true
        ;;
    catchup)
        stellar-core --catchup-complete
        ;;
    esac
done

exec stellar-core $STELLAR_OPTIONS
